# Generated by Django 4.1.3 on 2022-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileBanner',
            field=models.ImageField(blank=True, default='assets/default-banner.png', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='assets/default-profile-pic.jpeg', null=True, upload_to='img'),
        ),
    ]
