# Generated by Django 4.1.3 on 2022-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_profilebanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileBanner',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
