# Generated by Django 4.1.3 on 2022-11-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackpedia_app', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
